-- explore the data
select * from mdc;

-- explore the unique values
select distinct entity from mdc;
select distinct year from mdc
order by year;

-- Q1: Total revenue generated by marvel and dc movies
select sum(imdb_gross_millions) as total_gross_millions, 
       entity
from mdc
group by 2
order by 1 desc;
-- Around 13 billion for marvel and just 5 billions for DC

-- Q2: Oldest marvel and dc movie
select year,title, entity
from mdc
order by 1
limit 2;
-- 1944, Captain America :MARVEL  ; 1951,Superman and the Mole-Men:	DC

-- Q3: a. Highest imdb rated marvel and dc movie
select imdb_rating,title,year, entity
from mdc
order by 1 desc
limit 2;
-- rating:9 - The Dark Knight released in 2008 belongs to DC, rating:8.4 Avengers:infinity war released in 2018 belongs to Marvel

-- b. Highest rotten tomato rated marvel and dc movie
select year, mdc.title, tomato_meter,mdc.entity
from mdc
join (
    select entity, max(tomato_meter) as highest_rating
    from mdc
    group by entity
) as highest
on mdc.entity = highest.entity and mdc.tomato_meter = highest.highest_rating
limit 2;
-- rating: 96-Black Panther released in 2018 belongs to Marvel, rating: 94- superman released in 1978 belongs to DC

-- Q4: highest rated movie for marvel and dc
select mdc.year, mdc.title, mdc.entity, mdc.imdb_rating + mdc.tomato_meter as Total_ratings
from mdc
join(
    select entity, max(imdb_rating + tomato_meter) as Total_ratings
    from mdc
    group by entity
) as total
on mdc.entity = total.entity and (mdc.imdb_rating + mdc.tomato_meter) = total.Total_ratings
order by Total_ratings desc;
-- Black panther which was released in 2018 was the highest rated for marvel(103.3) while the dark knight was highest rated for dc (103 ratings) 

--Q5: which is highest rated, marvel or dc?
select entity, sum(imdb_rating + tomato_meter) as Total_ratings
from mdc
group by entity
order by Total_ratings desc;
-- highest rated is marvel with around 4047 ratings and DC with 1933 ratings

--Q6: which genre is most popular?
select genre, count(*) as genre_count
from (
    select genre_1 as genre from mdc
    union all
    select genre_2 from mdc
    union all
    select genre_3 from mdc
) as all_genres
group by genre
order by genre_count desc
limit 3;
-- action-most popular followed by adventure and sci-fi

--Q7: Most no. of movies by a director
select director,entity, count(*) as no_of_movies
from mdc
group by director, entity
order by no_of_movies desc
limit 3;
-- for marvel:Bryan Singer, Anthony Russo had most no. of movies and for DC, it's Zack Snyder (all of them had 4 movies)

--Q8: highest gross income
select mdc.title, mdc.entity, mdc.imdb_gross_millions
from mdc
join(
     select mdc.entity , max(imdb_gross_millions) as highest_revenue
     from mdc
     group by mdc.entity) as highest
on mdc.entity = highest.entity and mdc.imdb_gross_millions = highest.highest_revenue
order by 3 desc;
-- Avengers: Endgame generated highest revenue for marvel (around 858 millions) whereas The dark knight for DC(around 534 milllion)

--Q9: which director made films for both marvel and dc?
select director
from mdc
where entity in ('MARVEL', 'DC')
group by director
having count(distinct entity) = 2;
-- Bryan Singer

--Q10: which movies bryan singer directed?
select director, entity, title
from mdc
where director = 'Bryan Singer'
-- In marvel: X-men series and DC: superman returns
